#pragma once
#include "TransformComponent.h"
#include "SpriteComponent.h"
#include "StatComponent.h"
#include "ColliderComponent.h"
#include "StateComponent.h"
#include "RectComponent.h"
#include "ParentComponent.h"
#include "TextComponent.h"