#pragma once
#include "Scene_Grid.h"
#include "Scene_Camera.h"
#include "Scene_Spawn.h"
#include "Scene_Platformer.h"
#include "Scene_Editor.h"
#include "Scene_Ballbouncegame.h"
#include "Scene_GOL.h"
#include "Scene_Poker.h"